import fs from 'node:fs';
import path from 'node:path';
import { log } from '@scripts/lib/logger';
import { writeFilePath } from '@scripts/lib/write-file';
import { lookup } from '@utils/paths';

const ROOT = lookup('@');
const OUTPUT_FILE = lookup('@', 'generated', 'env.ts');

const ENV_FILES = fs.existsSync(ROOT)
  ? fs.readdirSync(ROOT).filter((f) => f.startsWith('.env') && !f.endsWith('.example'))
  : [];
const SKIP_KEYS = new Set(['NODE_ENV']);
const PRIVATE_PREFIX = 'PRIVATE_';
const SECRET_PATTERN = /(?:TOKEN|SECRET|PASSWORD|PASSPHRASE|CREDENTIAL|API_KEY|PRIVATE_KEY)/i;

type EnvType = 'string' | 'number' | 'boolean';

interface ParsedKey {
  key: string;
  value: string;
  type: EnvType;
  isPrivate: boolean;
}

function parseEnvFile(filePath: string): ParsedKey[] {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf-8');
  const results: ParsedKey[] = [];

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;

    const rawKey = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    let key = rawKey;
    let isPrivate = false;
    if (rawKey.startsWith(PRIVATE_PREFIX)) {
      key = rawKey.slice(PRIVATE_PREFIX.length);
      isPrivate = true;
    }

    if (SKIP_KEYS.has(key)) continue;
    results.push({ key, value, type: inferType(value), isPrivate });
  }
  return results;
}

function inferType(value: string): EnvType {
  if (value === 'true' || value === 'false') return 'boolean';
  if (/^-?\d+$/.test(value)) return 'number';
  return 'string';
}

function emptyDefault(type: EnvType): string {
  if (type === 'number') return '0';
  if (type === 'boolean') return 'false';
  return "''";
}

const schema = new Map<string, EnvType>();
const privateKeys = new Set<string>();

for (const file of ENV_FILES) {
  for (const entry of parseEnvFile(path.join(ROOT, file))) {
    if (!schema.has(entry.key)) {
      schema.set(entry.key, entry.type);
    }
    if (entry.isPrivate) {
      privateKeys.add(entry.key);
    }
  }
}

if (schema.size === 0) {
  log.warn('No .env files found — keeping existing generated/env.ts');
  process.exit(0);
}

for (const key of schema.keys()) {
  if (!privateKeys.has(key) && SECRET_PATTERN.test(key) && key !== 'STAGE') {
    log.warn(`[env] "${key}" looks like a secret but has no PRIVATE_ prefix — will be exposed to browser`);
  }
}

const sortedKeys = Array.from(schema.keys()).sort();
const browserKeys = sortedKeys.filter((k) => !privateKeys.has(k));
const privateKeyList = sortedKeys.filter((k) => privateKeys.has(k));

const browserSchemaEntries = browserKeys
  .map((key) => `  ${key}: { type: '${schema.get(key)}', default: ${emptyDefault(schema.get(key) as EnvType)} }`)
  .join(',\n');

const fullSchemaEntries = sortedKeys
  .map((key) => `      ${key}: { type: '${schema.get(key)}', default: ${emptyDefault(schema.get(key) as EnvType)} }`)
  .join(',\n');

const keyMapEntries = privateKeyList.map((key) => `      ${key}: '${PRIVATE_PREFIX + key}'`).join(',\n');

const browserArray = browserKeys.map((k) => `'${k}'`).join(', ');

const privateTypeEntries = privateKeyList.map((key) => `  ${key}: { type: '${schema.get(key)}' }`).join(',\n');

const output = `/**
 * Generated by: packages/env/cli/generate-env.ts
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated when .env files change.
 */

export const STAGES = ['dev', 'qa', 'uat', 'preprod', 'prod'] as const;

const BROWSER_SCHEMA = {
${browserSchemaEntries},
} as const;

const BROWSER_ENV_KEYS = [${browserArray}] as const;

type SchemaToType<S extends Record<string, { type: string }>> = {
  [K in keyof S]: S[K]['type'] extends 'number'
    ? number
    : S[K]['type'] extends 'boolean'
      ? boolean
      : string;
};

type FullSchema = typeof BROWSER_SCHEMA & {
${privateTypeEntries}
};

export type TypedEnv = SchemaToType<FullSchema> & { IS_PROD: boolean };

export type BrowserEnvType = Pick<TypedEnv, (typeof BROWSER_ENV_KEYS)[number]>;

function readEnv(): TypedEnv {
  if (import.meta.env.BROWSER) {
    const source = (import.meta.env ?? {}) as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const key of BROWSER_ENV_KEYS) {
      result[key] = source[key];
    }
    const stage = (result.STAGE as (typeof STAGES)[number]) ?? 'dev';
    return { ...result, STAGE: stage, IS_PROD: stage === 'prod' } as TypedEnv;
  }

  const ENV_SCHEMA = {
${fullSchemaEntries},
  } as const;

  const ENV_KEY_MAP: Record<string, string> = {
${keyMapEntries},
  };

  function validateValue(raw: unknown, type: 'string' | 'number' | 'boolean'): unknown {
    if (raw === undefined || raw === null) return undefined;
    if (type === 'boolean') {
      if (typeof raw === 'boolean') return raw;
      if (raw === 'true') return true;
      if (raw === 'false') return false;
      return undefined;
    }
    if (type === 'number') {
      if (typeof raw === 'number') return raw;
      const num = Number(raw);
      if (!Number.isNaN(num)) return num;
      return undefined;
    }
    if (typeof raw === 'string') return raw;
    return String(raw);
  }

  const source = process.env ?? {};
  const values: Record<string, unknown> = {};

  for (const key of Object.keys(ENV_SCHEMA)) {
    const field = ENV_SCHEMA[key as keyof typeof ENV_SCHEMA];
    const lookupKey = ENV_KEY_MAP[key] ?? key;
    const raw = source[lookupKey];
    const validated = validateValue(raw, field.type);
    values[key] = validated ?? field.default;
  }

  const stage = (values.STAGE as (typeof STAGES)[number]) ?? 'dev';
  return { ...values, STAGE: stage, IS_PROD: stage === 'prod' } as TypedEnv;
}

export async function loadServerEnvFiles(): Promise<void> {
  if (typeof process === 'undefined' || !process.versions?.node) return;

  const moduleName = 'node:module';
  const moduleRef = (await import(/* webpackIgnore: true */ moduleName)) as {
    createRequire: (path: string) => NodeRequire;
  };

  const dynamicRequire = moduleRef.createRequire(import.meta.url);
  const fs = dynamicRequire('node:fs') as typeof import('node:fs');
  const path = dynamicRequire('node:path') as typeof import('node:path');

  const cwd = process.cwd();
  const stage = (process.env.STAGE as (typeof STAGES)[number] | undefined) ?? 'dev';
  const files = ['.env', \`.env.\${stage}\`];

  for (const file of files) {
    const filePath = path.resolve(cwd, file);
    if (!fs.existsSync(filePath)) continue;

    const content = fs.readFileSync(filePath, 'utf-8');

    for (const line of content.split(/\\r?\\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const eq = trimmed.indexOf('=');
      if (eq === -1) continue;

      const key = trimmed.slice(0, eq).trim();
      let value = trimmed.slice(eq + 1).trim();

      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      if (!(key in process.env)) {
        process.env[key] = value;
      }
    }
  }
}

export const env: TypedEnv = readEnv();

export const browserEnv = Object.fromEntries(
  BROWSER_ENV_KEYS.map((k) => [k, env[k as keyof typeof env]]),
) as BrowserEnvType;
`;

writeFilePath(OUTPUT_FILE, output);
log.success(
  `Generated env — ${schema.size} key(s), ${privateKeys.size} private: ${[...privateKeys].sort().join(', ') || 'none'}`,
);
