/**
 * Generated by: packages/cli/generators/service-worker.ts
 * Generated at: {{codegen:generated_at}}
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated.
 */

const CACHE_NAME = {{codegen:cache_version}};
const BASE = new URL('.', self.location.href).pathname;
const ERROR_PAGES = [
  `${BASE}{{codegen:not_found_slug}}.html`,
  `${BASE}{{codegen:unauthorized_slug}}.html`,
  `${BASE}{{codegen:forbidden_slug}}.html`,
  `${BASE}{{codegen:server_error_slug}}.html`,
  `${BASE}{{codegen:maintenance_slug}}.html`,
  `${BASE}{{codegen:offline_error_slug}}.html`,
];
const PRECACHE_URLS = [BASE, ...ERROR_PAGES, `${BASE}manifest.json`];

const logCacheError = (context, url) => {
  console.warn(`[SW] Cache error in ${context}: ${url}`);
};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).catch((err) => {
      console.warn('[SW] Precache failed:', err);
    }),
  );
  self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  if (!request.url.startsWith(self.location.origin)) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('navigate', request.url));
          return response;
        })
        .catch(() =>
          caches.match(request).then((cached) => cached || caches.match(`${BASE}{{codegen:offline_slug}}.html`)),
        ),
    );
    return;
  }

  const isI18nAsset = request.url.includes('/{{codegen:i18n_asset_dir}}/');
  if (isI18nAsset) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) {
          fetch(request)
            .then((response) => {
              if (response?.status === 200 && response.type !== 'opaque') {
                const clone = response.clone();
                caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('i18n', request.url));
              }
            })
            .catch((err) => logCacheError('i18n fetch', request.url));
          return cached;
        }
        return fetch(request)
          .then((response) => {
            if (response?.status === 200 && response.type !== 'opaque') {
              const clone = response.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('i18n', request.url));
            }
            return response;
          })
          .catch(() => cached);
      }),
    );
    return;
  }

  const isStaticAsset = /.(js|css|woff2?|png|jpg|jpeg|webp|svg|gif|ico|avif|webm|mp4)$/.test(request.url);
  if (isStaticAsset) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) {
          fetch(request)
            .then((response) => {
              if (response?.status === 200 && response.type !== 'opaque') {
                const clone = response.clone();
                caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('static', request.url));
              }
            })
            .catch((err) => logCacheError('static fetch', request.url));
          return cached;
        }
        return fetch(request)
          .then((response) => {
            if (response?.status === 200 && response.type !== 'opaque') {
              const clone = response.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('static', request.url));
            }
            return response;
          })
          .catch(() => cached);
      }),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response?.status === 200 && response.type !== 'opaque') {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, clone)).catch((err) => logCacheError('general', request.url));
          }
          return response;
        })
        .catch(() => cached);
    }),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.map((n) => (n === CACHE_NAME ? null : caches.delete(n))))),
  );
  self.clients.claim();
});
