import fs from 'node:fs';
import { basename, dirname } from 'pathe';
import { PUBLIC_FILENAMES } from '@constants';

export const COMMENT_EXCLUDED_FILES = [
  PUBLIC_FILENAMES.sitemap,
  PUBLIC_FILENAMES.robots,
  PUBLIC_FILENAMES.manifest,
  PUBLIC_FILENAMES.faviconSvg,
  'og-image.svg',
] as const;

export interface GeneratedHeaderOptions {
  description?: string;
}

export function writeFilePath(filePath: string, content: string): void {
  fs.mkdirSync(dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

export function generatedHeader(toolName: string, options?: GeneratedHeaderOptions): string {
  const timestamp = new Date().toISOString();
  const lines = ['/**', ` * Generated by: ${toolName}`, ` * Generated at: ${timestamp}`];

  if (options?.description) {
    lines.push(' *');
    for (const desc of options.description.split('\n')) {
      lines.push(` * ${desc}`);
    }
  }

  lines.push(' *', ' * WARNING: DO NOT EDIT MANUALLY', ' * This file is automatically updated.', ' */');
  return lines.join('\n');
}

export function shouldAddComment(filePath: string): boolean {
  const fileName = basename(filePath);
  return !(COMMENT_EXCLUDED_FILES as readonly string[]).includes(fileName);
}

export function withGeneratedHeader(
  filePath: string,
  toolName: string,
  content: string,
  options?: GeneratedHeaderOptions,
): string {
  return shouldAddComment(filePath) ? `${generatedHeader(toolName, options)}\n\n${content}` : content;
}
