import fs from 'node:fs';
import path from 'node:path';

export function writeFilePath(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

export function generatedHeader(toolName: string): string {
  const timestamp = new Date().toISOString();
  return [
    '/**',
    ` * Generated by: ${toolName}`,
    ` * Generated at: ${timestamp}`,
    ' *',
    ' * WARNING: DO NOT EDIT MANUALLY',
    ' * This file is automatically updated.',
    ' */',
  ].join('\n');
}
