import fs from 'node:fs';
import path from 'node:path';
import { i18nConfig } from '@config/i18n';
import { resolveRoot } from '@config/paths';
import { buildFontsCss } from '@i18n/fonts/font-css';
import { log, logBox } from './lib/logger';

const OUTPUT_DIR = resolveRoot('public', 'assets', 'fonts');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'fonts.css');

const allLocales = [i18nConfig.defaultLocale, ...(i18nConfig.locales ?? [])];
const packageCss = buildFontsCss(allLocales);

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

if (packageCss.length > 0) {
  const header = `/* Generated by scripts/generate-fonts-css.ts\n * Active locales: ${allLocales.join(', ')}\n * Do not edit manually.\n */\n\n`;
  const combined = packageCss.map((p) => p.css).join('\n\n');
  fs.writeFileSync(OUTPUT_FILE, header + combined, 'utf-8');
} else {
  if (fs.existsSync(OUTPUT_FILE)) {
    fs.unlinkSync(OUTPUT_FILE);
  }
}

logBox('Generate Fonts CSS', {
  Locales: allLocales.join(', '),
  Packages: packageCss.map((p) => `${path.basename(p.pkg)} (${p.subsetCount})`).join(', ') || '(none)',
  Output: 'public/assets/fonts/fonts.css',
});
log.success(
  `Done: ${packageCss.length} font package(s), ${packageCss.reduce((s, p) => s + p.subsetCount, 0)} subset(s) total`,
);
