import fs from 'node:fs';
import path from 'node:path';
import { BASE_CURRENCY, LOCALES } from '../src/configs/locales';
import { EXCHANGE_RATES_URL, PATHS } from '../src/configs/paths';

const GENERATED_DIR = path.resolve(process.cwd(), PATHS.GENERATED);
const EXCHANGE_RATES_FILE = path.resolve(GENERATED_DIR, 'exchange-rates.ts');

const LOCALE_CURRENCIES = [...new Set(LOCALES.map((l) => l.currency))];

async function fetchExchangeRates(): Promise<Record<string, number>> {
  const quotes = LOCALE_CURRENCIES.filter((c) => c !== BASE_CURRENCY).join(',');
  const url = `${EXCHANGE_RATES_URL}?base=${BASE_CURRENCY}${quotes ? `&quotes=${quotes}` : ''}`;

  console.log(`Fetching from: ${url}`);

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch exchange rates: ${response.statusText}`);
  }

  const data = await response.json() as Array<{ quote: string; rate: number }>;

  const ratesObj: Record<string, number> = {
    [BASE_CURRENCY]: 1,
  };

  for (const item of data) {
    ratesObj[item.quote] = item.rate;
  }

  return ratesObj;
}

function formatRatesObject(rates: Record<string, number>): string {
  const entries = Object.entries(rates)
    .sort(([, a], [, b]) => a - b)
    .map(([key, value]) => `  ${key}: ${value.toFixed(8)}`)
    .join(',\n');
  return `{\n${entries}\n}`;
}

async function loadExistingRates(): Promise<{ lastUpdated: Date } | null> {
  if (fs.existsSync(EXCHANGE_RATES_FILE)) {
    try {
      const stats = await fs.promises.stat(EXCHANGE_RATES_FILE);
      return { lastUpdated: stats.mtime };
    } catch {
      return null;
    }
  }
  return null;
}

function isRatesFresh(data: { lastUpdated: Date }): boolean {
  const now = new Date();
  const hoursSinceUpdate = (now.getTime() - data.lastUpdated.getTime()) / (1_000 * 60 * 60);
  return hoursSinceUpdate < 24;
}

async function generateExchangeRates(forceRefresh = false): Promise<void> {
  console.log('Exchange rates generator starting...');

  const existing = await loadExistingRates();

  if (!forceRefresh && existing && isRatesFresh(existing)) {
    console.log('Using cached exchange rates (last updated:', existing.lastUpdated + ')');
    return;
  }

  console.log('Fetching exchange rates from Frankfurter API');
  console.log(`Currencies: ${LOCALE_CURRENCIES.join(', ')}`);

  try {
    const rates = await fetchExchangeRates();

    console.log(`Fetched ${Object.keys(rates).length} exchange rates:`);
    for (const [currency, rate] of Object.entries(rates)) {
      console.log(`  1 ${BASE_CURRENCY} = ${rate.toFixed(4)} ${currency}`);
    }

    if (!fs.existsSync(GENERATED_DIR)) {
      fs.mkdirSync(GENERATED_DIR, { recursive: true });
    }

    const content = `/**
 * Auto-generated exchange rates
 * Source: https://frankfurter.dev/
 * Generated by: tools/fetch-exchange-rates.ts
 * Generated at: ${new Date().toISOString()}
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated. Run \`bun run fetch:rates\` to refresh.
 */

export const EXCHANGE_RATES = ${formatRatesObject(rates)} as const;

export function convertCurrency(
  amount: number,
  from: string,
  to: string,
  rates: Record<string, number> = EXCHANGE_RATES
): number {
  if (from === to) return amount;

  const fromRate = rates[from];
  const toRate = rates[to];

  if (!fromRate || !toRate) {
    const missing = !fromRate ? from : to;
    console.warn(\`[i18n] Currency not supported: \${missing}. Available: \${Object.keys(rates).join(', ')}\`);
    return amount;
  }

  const inBase = amount / fromRate;
  return inBase * toRate;
}
`;

    fs.writeFileSync(EXCHANGE_RATES_FILE, content);

    console.log('Exchange rates saved to', EXCHANGE_RATES_FILE);
    console.log('Last updated:', new Date().toISOString());
  } catch (error) {
    console.error('Failed to generate exchange rates:', error);

    if (!existing) {
      throw error;
    }
    console.log('Using existing cached rates as fallback');
  }
}

const args = process.argv.slice(2);
const forceRefresh = args.includes('--force') || args.includes('-f');

generateExchangeRates(forceRefresh)
  .then(() => {
    console.log('Exchange rates generation completed');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Exchange rates generation failed:', error);
    process.exit(1);
  });
