/**
 * Generated by: packages/env/cli/generate-env.ts
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated when .env files change.
 */

export const STAGES = ['dev', 'qa', 'uat', 'preprod', 'prod'] as const;

const BROWSER_SCHEMA = {
{{codegen:browser_schema_entries}}
} as const;

const BROWSER_ENV_KEYS = [{{codegen:browser_keys}}] as const;

type SchemaToType<S extends Record<string, { type: string }>> = {
  [K in keyof S]: S[K]['type'] extends 'number'
    ? number
    : S[K]['type'] extends 'boolean'
      ? boolean
      : string;
};

type FullSchema = typeof BROWSER_SCHEMA & {
{{codegen:private_type_entries}}
};

export type TypedEnv = SchemaToType<FullSchema> & { IS_PROD: boolean };

export type BrowserEnvType = Pick<TypedEnv, (typeof BROWSER_ENV_KEYS)[number]>;

function readEnv(): TypedEnv {
  if (import.meta.env.BROWSER) {
    const source = (import.meta.env ?? {}) as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const key of BROWSER_ENV_KEYS) {
      result[key] = source[key];
    }
    const stage = (result.STAGE as (typeof STAGES)[number]) ?? 'dev';
    return { ...result, STAGE: stage, IS_PROD: stage === 'prod' } as TypedEnv;
  }

  const ENV_SCHEMA = {
{{codegen:full_schema_entries}}
  } as const;

  const ENV_KEY_MAP: Record<string, string> = {
{{codegen:key_map_entries}}
  };

  function validateValue(raw: unknown, type: 'string' | 'number' | 'boolean'): unknown {
    if (raw === undefined || raw === null) return undefined;
    if (type === 'boolean') {
      if (typeof raw === 'boolean') return raw;
      if (raw === 'true') return true;
      if (raw === 'false') return false;
      return undefined;
    }
    if (type === 'number') {
      if (typeof raw === 'number') return raw;
      const num = Number(raw);
      if (!Number.isNaN(num)) return num;
      return undefined;
    }
    if (typeof raw === 'string') return raw;
    return String(raw);
  }

  const source = process.env ?? {};
  const values: Record<string, unknown> = {};

  for (const key of Object.keys(ENV_SCHEMA)) {
    const field = ENV_SCHEMA[key as keyof typeof ENV_SCHEMA];
    const lookupKey = ENV_KEY_MAP[key] ?? key;
    const raw = source[lookupKey];
    const validated = validateValue(raw, field.type);
    values[key] = validated ?? field.default;
  }

  const stage = (values.STAGE as (typeof STAGES)[number]) ?? 'dev';
  return { ...values, STAGE: stage, IS_PROD: stage === 'prod' } as TypedEnv;
}

export async function loadServerEnvFiles(): Promise<void> {
  if (typeof process === 'undefined' || !process.versions?.node) return;

  const moduleName = 'node:module';
  const moduleRef = (await import(/* webpackIgnore: true */ moduleName)) as {
    createRequire: (path: string) => NodeRequire;
  };

  const dynamicRequire = moduleRef.createRequire(import.meta.url);
  const fs = dynamicRequire('node:fs') as typeof import('node:fs');
  const path = dynamicRequire('node:path') as typeof import('node:path');

  const cwd = process.cwd();
  const stage = (process.env.STAGE as (typeof STAGES)[number] | undefined) ?? 'dev';
  const files = ['.env', `.env.${stage}`];

  for (const file of files) {
    const filePath = path.resolve(cwd, file);
    if (!fs.existsSync(filePath)) continue;

    const content = fs.readFileSync(filePath, 'utf-8');

    for (const line of content.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const eq = trimmed.indexOf('=');
      if (eq === -1) continue;

      const key = trimmed.slice(0, eq).trim();
      let value = trimmed.slice(eq + 1).trim();

      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      if (!(key in process.env)) {
        process.env[key] = value;
      }
    }
  }
}

export const env: TypedEnv = readEnv();

export const browserEnv = Object.fromEntries(
  BROWSER_ENV_KEYS.map((k) => [k, env[k as keyof typeof env]]),
) as BrowserEnvType;
