/**
 * Generated by: scripts/fetch-exchange-rates.ts
 * Generated at: {{codegen:generated_at}}
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated.
 */

export const EXCHANGE_RATES = {
{{codegen:rates_object}}
} as const;

export function convertCurrency(
  amount: number,
  from: string,
  to: string,
  rates: Record<string, number> = EXCHANGE_RATES
): number {
  if (from === to) return amount;

  const fromRate = rates[from];
  const toRate = rates[to];

  if (!fromRate || !toRate) return amount;

  const inBase = amount / fromRate;
  return inBase * toRate;
}
