/**
 * Generated by: scripts/generators/generate-paths.ts
 * Generated at: {{codegen:generated_at}}
 *
 * WARNING: DO NOT EDIT MANUALLY
 * This file is automatically updated.
 */

import fs from 'node:fs';
import path from 'node:path';

export type AliasKey =
{{codegen:alias_keys}};

export const alias: Record<AliasKey, string> = {
{{codegen:alias_entries}}
};

export function lookup(key: AliasKey, ...parts: string[]): string {
  return path.join(alias[key], ...parts);
}

export function find(key: AliasKey, ...parts: string[]): string | null {
  const candidate = lookup(key, ...parts);
  return fs.existsSync(candidate) ? candidate : null;
}
